# Generated by Django 5.1.4 on 2024-12-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auctionitem_watched_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionitem",
            name="current_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="starting_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
